# Generated by Django 3.0.5 on 2020-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
