# Generated by Django 3.0.5 on 2020-04-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
