# Generated by Django 3.0.5 on 2020-05-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='label',
            new_name='title',
        ),
    ]
