# Generated by Django 3.0.5 on 2020-05-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_auto_20200505_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 14, 8, 39, 833071)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
