# Generated by Django 3.0.5 on 2020-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_auto_20200505_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image_link',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
