# Generated by Django 3.0.5 on 2020-05-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_auto_20200505_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
