# Generated by Django 3.0.5 on 2020-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0009_auto_20200505_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_link',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
