version: '3.8'

services:
    db:
        image: postgres
        restart: always
        container_name: 'news_parser_postgre'
        environment: 
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USER}'
            POSTGRES_DB: '${DB_NAME}'
        ports: 
            - '${DB_PORT}:${DB_PORT}'                
