# Generated by Django 3.0.5 on 2020-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssite',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='newssite',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
