# Generated by Django 3.0.5 on 2020-05-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20200505_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleNewsSite',
        ),
    ]
